# -------------------------------------------------------------------
# Stage 0
# Build Angular application.
# -------------------------------------------------------------------
FROM node:8-slim as build-stage

ENV PATH /knoweak/node_modules/.bin:$PATH

WORKDIR /knoweak/

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# -------------------------------------------------------------------
# Final stage
# Create nginx image with static files generated in previous stage.
# -------------------------------------------------------------------
FROM nginx:1-alpine

COPY --from=build-stage /knoweak/dist /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf