# -------------------------------------------------------------------
# Stage 0
# Build Angular application.
# -------------------------------------------------------------------
FROM node:8-slim as build-stage

ENV PATH /knoweak/node_modules/.bin:$PATH

COPY package*.json /knoweak/

WORKDIR /knoweak/
RUN npm install

COPY . /knoweak/
RUN npm run build

# -------------------------------------------------------------------
# Final stage
# Create nginx image with static files generated in previous stage.
# -------------------------------------------------------------------
FROM nginx:1-alpine

COPY --from=build-stage /knoweak/dist /usr/share/nginx/html